name: First Github Action
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Welcome to github"
      - name:
        run: |
          node -v
          npm -v
          systemctl status docker.service